TOOL_CATALOG = {
    "ciclos": [
        "ciclo_visao_geral",
        "ciclo_problema_principal",
        "ciclo_causas_raiz",
        "ciclo_ishikawa",
        "ciclo_riscos_pendencias",
        "ciclo_treinamentos",
        "ciclo_participantes",
        "ciclo_relatorio_completo",
    ],
    "tarefas": [
        "tarefas_consultar",
        "tarefas_atrasadas",
        "tarefas_concluidas",
        "tarefas_detalhes",
        "tarefas_por_responsavel",
        "tarefas_alertas_prazo",
        "tarefas_justificativas",
        "tarefas_relatorio_completo",
    ],
    "colaboradores": [
        "colaboradores_consultar",
        "colaborador_detalhes",
        "colaboradores_participantes_ciclo",
        "colaboradores_por_area",
        "colaboradores_carga_trabalho",
        "colaboradores_competencias",
        "colaboradores_disponibilidade",
        "colaboradores_realocacoes",
        "colaboradores_sugestao_realocacao",
        "colaboradores_relatorio_completo",
    ],
    "formularios": [
        "formularios_listar",
        "formularios_detalhes",
        "formularios_respostas",
        "formularios_resumo_respostas",
    ],
    "relatorios": [
        "relatorios_listar",
        "relatorios_detalhes",
        "relatorios_mais_recente",
        "relatorios_contexto_ciclo",
    ],
    "predicoes": [
        "predicoes_risco_atraso_tarefa",
        "predicoes_estimativa_conclusao_tarefa",
        "predicoes_risco_atraso_ciclo",
        "predicoes_estimativa_conclusao_ciclo",
        "predicoes_conclusao_treinamento",
        "predicoes_sobrecarga_colaborador",
        "predicoes_atingimento_meta",
        "predicoes_respostas_atipicas",
        "predicoes_tema_formulario",
        "predicoes_recorrencia_problema",
    ],
    "memoria": [
        "memoria_garantir_sessao",
        "memoria_salvar_mensagem",
        "memoria_obter_contexto",
        "memoria_material_resumo",
        "memoria_atualizar_resumo",
        "memoria_registrar",
        "memoria_buscar",
        "memoria_listar",
        "memoria_excluir",
        "memoria_obter_consentimento",
        "memoria_configurar_consentimento",
    ],
    "rag": ["faq_retriever"],
}
