TOOL_CATALOG = {
    "ciclos": [
        "ciclo_visao_geral",
        "ciclo_problema_principal",
        "ciclo_causas_raiz",
        "ciclo_ishikawa",
        "ciclo_riscos_pendencias",
        "ciclo_treinamentos",
        "ciclo_participantes",
        "ciclo_relatorio_completo",
        "ciclos_registrar_causa",
        "ciclos_adicionar_item_ishikawa",
    ],
    "tarefas": [
        "tarefas_consultar",
        "tarefas_atrasadas",
        "tarefas_concluidas",
        "tarefas_detalhes",
        "tarefas_por_responsavel",
        "tarefas_alertas_prazo",
        "tarefas_relatorio_completo",
        "tarefas_criar",
        "tarefas_atualizar",
        "tarefas_atualizar_status",
    ],
    "colaboradores": [
        "colaboradores_consultar",
        "colaborador_detalhes",
        "colaboradores_participantes_ciclo",
        "colaboradores_por_area",
        "colaboradores_carga_trabalho",
        "colaboradores_sugestao_realocacao",
        "colaboradores_relatorio_completo",
    ],
    "formularios": [
        "formularios_listar",
        "formularios_detalhes",
        "formularios_respostas",
        "formularios_resumo_respostas",
        "formularios_criar_rascunho",
        "formularios_adicionar_pergunta",
        "formularios_publicar",
    ],
    "relatorios": [
        "relatorios_contexto_ciclo",
    ],
    "predicoes": [
        "predicoes_risco_atraso_tarefa",
        "predicoes_estimativa_conclusao_tarefa",
        "predicoes_risco_atraso_ciclo",
        "predicoes_estimativa_conclusao_ciclo",
        "predicoes_conclusao_treinamento",
        "predicoes_sobrecarga_colaborador",
        "predicoes_atingimento_meta",
        "predicoes_respostas_atipicas",
        "predicoes_tema_formulario",
        "predicoes_recorrencia_problema",
    ],
    "memoria": [
        "memoria_garantir_sessao",
        "memoria_salvar_mensagem",
        "memoria_obter_contexto",
        "memoria_material_resumo",
        "memoria_encerrar_sessao",
        "memoria_listar_chats",
        "memoria_atualizar_resumo",
        "memoria_registrar",
        "memoria_buscar",
        "memoria_listar",
        "memoria_excluir",
        "memoria_obter_consentimento",
        "memoria_configurar_consentimento",
    ],
    "rag": ["faq_retriever"],
    "skills": ["skills_criar", "skills_obter", "skills_listar", "skills_excluir"],
    "licoes_aprendidas": ["licoes_aprendidas_registrar"],
    "treinamentos": ["treinamentos_criar"],
}
